# -*- coding: utf-8 -*-
"""Progres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N1ZPDtOoP4koE-ZWuUBiNPTyZKNefuFs

# Libraries:
- [progress](https://github.com/verigak/progress/);
- [tqdm](https://github.com/tqdm/tqdm)
- [alive-progress](https://github.com/rsalmei/alive-progress)
- [sys](https://stackoverflow.com/questions/3160699/python-progress-bar)
- [clint](https://github.com/kennethreitz-archive/clint)

# [progress](https://github.com/verigak/progress/)
"""

#!pip install progress

import time 
from progress.bar import IncrementalBar

mylist = [1,2,3,4,5,6,7,8]

bar = IncrementalBar('Countdown', max = len(mylist))

for item in mylist:
    bar.next()
    time.sleep(1)

bar.finish()
print("Done!")

"""## Bars
There are 7 progress bars to choose from:

- Bar
- ChargingBar
- FillingSquaresBar
- FillingCirclesBar
- IncrementalBar
- PixelBar
- ShadyBar

![](https://camo.githubusercontent.com/2eac4822edcfe3353ad2e4b56c33b6e4b4f8955f/68747470733a2f2f7261772e6769746875622e636f6d2f7665726967616b2f70726f67726573732f6d61737465722f64656d6f2e676966)

# [tqdm](https://github.com/tqdm/tqdm)
"""

import time
from tqdm import tqdm

mylist = [1,2,3,4,5,6]

for i in tqdm(mylist):
    time.sleep(1)

print("Done!")

"""![](https://raw.githubusercontent.com/tqdm/tqdm/master/images/tqdm.gif)

# [alive-progress](https://github.com/rsalmei/alive-progress)
"""

#!pip install alive_progress

import time
from alive_progress import alive_bar

mylist = [1,2,3,4,5]

with alive_bar(len(mylist)) as bar:
  for i in mylist:
    bar()
    time.sleep(0.5)

print("Done!")

"""![](https://raw.githubusercontent.com/rsalmei/alive-progress/master/img/alive-demo.gif)

# [sys](https://stackoverflow.com/questions/3160699/python-progress-bar)
"""

import time
import sys

toolbar_width = 40

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()


sys.stdout.write("]\n") # this ends the progress bar
print("Done!")

"""# [clint](https://github.com/kennethreitz-archive/clint)"""

#!pip install clint

from clint.textui import progress
import time

for i in progress.bar(range(10)):
    print("Bar")
    time.sleep(.1)

print("-----------------------------------------")
for i in progress.dots(range(10)):
    print("Dots")
    time.sleep(.1)

print("-----------------------------------------")
for i in progress.mill(range(10)):
    print("Mill")
    time.sleep(.1)
print("-----------------------------------------")
print("Done!")

"""### In this I dont tell about GUI progress bar. And many others...
As for me the best choice is tqdm. It is easy and practical.

# Sources

[habr](https://habr.com/ru/post/483400/)

[stackoverflow](https://stackoverflow.com/questions/3160699/python-progress-bar)

http://zetblog.ru/python-kak-sdelat-progress-bar-v-konsole.html
"""

